//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Game.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="Game"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IGameListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="Game.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] Game.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Game.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] Game.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Game.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] Game.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Game.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] Game.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Game.simpleCommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSimpleCommand([NotNull] Game.SimpleCommandContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Game.simpleCommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSimpleCommand([NotNull] Game.SimpleCommandContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Game.moveCommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMoveCommand([NotNull] Game.MoveCommandContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Game.moveCommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMoveCommand([NotNull] Game.MoveCommandContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Game.rotateCommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRotateCommand([NotNull] Game.RotateCommandContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Game.rotateCommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRotateCommand([NotNull] Game.RotateCommandContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Game.takeCommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTakeCommand([NotNull] Game.TakeCommandContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Game.takeCommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTakeCommand([NotNull] Game.TakeCommandContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Game.dropCommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDropCommand([NotNull] Game.DropCommandContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Game.dropCommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDropCommand([NotNull] Game.DropCommandContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Game.shieldCommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterShieldCommand([NotNull] Game.ShieldCommandContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Game.shieldCommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitShieldCommand([NotNull] Game.ShieldCommandContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Game.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfStatement([NotNull] Game.IfStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Game.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfStatement([NotNull] Game.IfStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Game.whileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhileStatement([NotNull] Game.WhileStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Game.whileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhileStatement([NotNull] Game.WhileStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Game.repeatStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRepeatStatement([NotNull] Game.RepeatStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Game.repeatStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRepeatStatement([NotNull] Game.RepeatStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Game.procedureDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProcedureDecl([NotNull] Game.ProcedureDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Game.procedureDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProcedureDecl([NotNull] Game.ProcedureDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Game.paramList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParamList([NotNull] Game.ParamListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Game.paramList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParamList([NotNull] Game.ParamListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Game.procedureCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProcedureCall([NotNull] Game.ProcedureCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Game.procedureCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProcedureCall([NotNull] Game.ProcedureCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Game.argList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgList([NotNull] Game.ArgListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Game.argList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgList([NotNull] Game.ArgListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Game.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] Game.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Game.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] Game.BlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Game.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignment([NotNull] Game.AssignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Game.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignment([NotNull] Game.AssignmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Game.condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCondition([NotNull] Game.ConditionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Game.condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCondition([NotNull] Game.ConditionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Game.comparison"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComparison([NotNull] Game.ComparisonContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Game.comparison"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComparison([NotNull] Game.ComparisonContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Game.compOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompOp([NotNull] Game.CompOpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Game.compOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompOp([NotNull] Game.CompOpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Game.predicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPredicate([NotNull] Game.PredicateContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Game.predicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPredicate([NotNull] Game.PredicateContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Game.direction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDirection([NotNull] Game.DirectionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Game.direction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDirection([NotNull] Game.DirectionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>IntLiteralExpr</c>
	/// labeled alternative in <see cref="Game.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIntLiteralExpr([NotNull] Game.IntLiteralExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>IntLiteralExpr</c>
	/// labeled alternative in <see cref="Game.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIntLiteralExpr([NotNull] Game.IntLiteralExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>MulDivExpr</c>
	/// labeled alternative in <see cref="Game.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMulDivExpr([NotNull] Game.MulDivExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>MulDivExpr</c>
	/// labeled alternative in <see cref="Game.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMulDivExpr([NotNull] Game.MulDivExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>VarExpr</c>
	/// labeled alternative in <see cref="Game.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarExpr([NotNull] Game.VarExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>VarExpr</c>
	/// labeled alternative in <see cref="Game.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarExpr([NotNull] Game.VarExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ParenExpr</c>
	/// labeled alternative in <see cref="Game.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParenExpr([NotNull] Game.ParenExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ParenExpr</c>
	/// labeled alternative in <see cref="Game.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParenExpr([NotNull] Game.ParenExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>AddSubExpr</c>
	/// labeled alternative in <see cref="Game.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAddSubExpr([NotNull] Game.AddSubExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>AddSubExpr</c>
	/// labeled alternative in <see cref="Game.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAddSubExpr([NotNull] Game.AddSubExprContext context);
}
