//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Game.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IGameListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class GameBaseListener : IGameListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="Game.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] Game.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Game.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] Game.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Game.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] Game.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Game.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] Game.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Game.simpleCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSimpleCommand([NotNull] Game.SimpleCommandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Game.simpleCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSimpleCommand([NotNull] Game.SimpleCommandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Game.moveCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMoveCommand([NotNull] Game.MoveCommandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Game.moveCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMoveCommand([NotNull] Game.MoveCommandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Game.rotateCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRotateCommand([NotNull] Game.RotateCommandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Game.rotateCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRotateCommand([NotNull] Game.RotateCommandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Game.takeCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTakeCommand([NotNull] Game.TakeCommandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Game.takeCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTakeCommand([NotNull] Game.TakeCommandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Game.dropCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDropCommand([NotNull] Game.DropCommandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Game.dropCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDropCommand([NotNull] Game.DropCommandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Game.shieldCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterShieldCommand([NotNull] Game.ShieldCommandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Game.shieldCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitShieldCommand([NotNull] Game.ShieldCommandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Game.ifStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfStatement([NotNull] Game.IfStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Game.ifStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfStatement([NotNull] Game.IfStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Game.whileStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhileStatement([NotNull] Game.WhileStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Game.whileStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhileStatement([NotNull] Game.WhileStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Game.repeatStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRepeatStatement([NotNull] Game.RepeatStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Game.repeatStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRepeatStatement([NotNull] Game.RepeatStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Game.procedureDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProcedureDecl([NotNull] Game.ProcedureDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Game.procedureDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProcedureDecl([NotNull] Game.ProcedureDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Game.paramList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParamList([NotNull] Game.ParamListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Game.paramList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParamList([NotNull] Game.ParamListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Game.procedureCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProcedureCall([NotNull] Game.ProcedureCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Game.procedureCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProcedureCall([NotNull] Game.ProcedureCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Game.argList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgList([NotNull] Game.ArgListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Game.argList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgList([NotNull] Game.ArgListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Game.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlock([NotNull] Game.BlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Game.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlock([NotNull] Game.BlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Game.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignment([NotNull] Game.AssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Game.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignment([NotNull] Game.AssignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Game.condition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCondition([NotNull] Game.ConditionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Game.condition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCondition([NotNull] Game.ConditionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Game.comparison"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComparison([NotNull] Game.ComparisonContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Game.comparison"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComparison([NotNull] Game.ComparisonContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Game.compOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCompOp([NotNull] Game.CompOpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Game.compOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCompOp([NotNull] Game.CompOpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Game.predicate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPredicate([NotNull] Game.PredicateContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Game.predicate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPredicate([NotNull] Game.PredicateContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Game.direction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDirection([NotNull] Game.DirectionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Game.direction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDirection([NotNull] Game.DirectionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>IntLiteralExpr</c>
	/// labeled alternative in <see cref="Game.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIntLiteralExpr([NotNull] Game.IntLiteralExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>IntLiteralExpr</c>
	/// labeled alternative in <see cref="Game.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIntLiteralExpr([NotNull] Game.IntLiteralExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>MulDivExpr</c>
	/// labeled alternative in <see cref="Game.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMulDivExpr([NotNull] Game.MulDivExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>MulDivExpr</c>
	/// labeled alternative in <see cref="Game.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMulDivExpr([NotNull] Game.MulDivExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>VarExpr</c>
	/// labeled alternative in <see cref="Game.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarExpr([NotNull] Game.VarExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>VarExpr</c>
	/// labeled alternative in <see cref="Game.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarExpr([NotNull] Game.VarExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ProcCallExpr</c>
	/// labeled alternative in <see cref="Game.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProcCallExpr([NotNull] Game.ProcCallExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ProcCallExpr</c>
	/// labeled alternative in <see cref="Game.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProcCallExpr([NotNull] Game.ProcCallExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ParenExpr</c>
	/// labeled alternative in <see cref="Game.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParenExpr([NotNull] Game.ParenExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ParenExpr</c>
	/// labeled alternative in <see cref="Game.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParenExpr([NotNull] Game.ParenExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>AddSubExpr</c>
	/// labeled alternative in <see cref="Game.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAddSubExpr([NotNull] Game.AddSubExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>AddSubExpr</c>
	/// labeled alternative in <see cref="Game.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAddSubExpr([NotNull] Game.AddSubExprContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
