//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Game.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="Game"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IGameVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="Game.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] Game.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Game.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] Game.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Game.simpleCommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimpleCommand([NotNull] Game.SimpleCommandContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Game.moveCommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMoveCommand([NotNull] Game.MoveCommandContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Game.rotateCommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRotateCommand([NotNull] Game.RotateCommandContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Game.takeCommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTakeCommand([NotNull] Game.TakeCommandContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Game.dropCommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDropCommand([NotNull] Game.DropCommandContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Game.shieldCommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitShieldCommand([NotNull] Game.ShieldCommandContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Game.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfStatement([NotNull] Game.IfStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Game.whileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhileStatement([NotNull] Game.WhileStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Game.repeatStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRepeatStatement([NotNull] Game.RepeatStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Game.procedureDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProcedureDecl([NotNull] Game.ProcedureDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Game.paramList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParamList([NotNull] Game.ParamListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Game.procedureCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProcedureCall([NotNull] Game.ProcedureCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Game.argList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgList([NotNull] Game.ArgListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Game.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock([NotNull] Game.BlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Game.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignment([NotNull] Game.AssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Game.condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCondition([NotNull] Game.ConditionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Game.comparison"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComparison([NotNull] Game.ComparisonContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Game.compOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompOp([NotNull] Game.CompOpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Game.predicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPredicate([NotNull] Game.PredicateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Game.direction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDirection([NotNull] Game.DirectionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>IntLiteralExpr</c>
	/// labeled alternative in <see cref="Game.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntLiteralExpr([NotNull] Game.IntLiteralExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MulDivExpr</c>
	/// labeled alternative in <see cref="Game.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMulDivExpr([NotNull] Game.MulDivExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>VarExpr</c>
	/// labeled alternative in <see cref="Game.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarExpr([NotNull] Game.VarExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ParenExpr</c>
	/// labeled alternative in <see cref="Game.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParenExpr([NotNull] Game.ParenExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AddSubExpr</c>
	/// labeled alternative in <see cref="Game.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAddSubExpr([NotNull] Game.AddSubExprContext context);
}
